---
title: "Facility MNH Queries"
subtitle: "Tool C"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  officedown::rdocx_document:
    reference_docx: "./style-reference.docx"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

# File description: Generates Word tables listing the flagged observations for each data query
# Word file: each row includes observation KEY, the question the query relates to, a brief description of the error, and a space for the data manager to respond to the query

library(here)
library(tidyr)
library(dplyr)
library(officedown)
library(officer)
library(flextable)
library(openxlsx)

# set path
mypath_results <- "C:/Users/HEilerts/Institute of International Programs Dropbox/Hallie Eilerts-Spinelli/MNHeval-HealthFacility/facility-mnh-nigeria/gen/monitoring/tables/"

# identify latest data queries excel file
v_files <- list.files(mypath_results)
v_files <- v_files[grepl("data-queries-toolC", v_files)]
latest_file <- tail(sort(v_files), 1)

# load sheets for each part of tool separately from excel file
dat <- openxlsx::read.xlsx(paste0(mypath_results, latest_file), sheet = "toolC-main")

# define flextable
fn_make_flextable <- function(dat) {
  dat %>%
    select(-KEY) %>%
    arrange(f03, question) %>%
    mutate(response = "") %>%
    flextable() %>%
    width(j = "f03", width = 1) %>% 
    width(j = "question", width = 1) %>% 
    width(j = "label", width = 2) %>% 
    width(j = "issue", width = 3) %>% 
    width(j = "response", width = 2) %>% 
    font(fontname = "Times New Roman", part = "all") %>%
    fontsize(size = 9, part = "all") %>%
    padding(padding = 2, part = "all") %>%
    border_inner_h(border = officer::fp_border(color = "black", width = 1), part = "body") %>%
    border_inner_v(border = officer::fp_border(color = "black", width = 1), part = "all")
}
```

```{r}
fn_make_flextable(dat)
```


